-- Mock data gennerated by https://www.mockaroo.com/ using AI
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Testing software', 'Create a login page with authentication functionality', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Refactoring code', 'Implement a RESTful API for user management', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Collaborating with team', 'Create a login page with authentication functionality', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Creating documentation', 'Develop a mobile app with offline functionality', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Troubleshooting issues', 'Create a documentation guide for API endpoints', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Meeting with stakeholders', 'Create a documentation guide for API endpoints', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Designing user interface', 'Refactor codebase to follow SOLID principles', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Researching new technologies', 'Implement a RESTful API for user management', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Deploying software', 'Write unit tests for a specific module', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Implementing new features', 'Implement a RESTful API for user management', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Designing user interface', 'Write unit tests for a specific module', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Collaborating with team', 'Optimize database queries for improved performance', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Troubleshooting issues', 'Develop a mobile app with offline functionality', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Maintaining codebase', 'Create a documentation guide for API endpoints', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Researching new technologies', 'Optimize database queries for improved performance', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Troubleshooting issues', 'Write unit tests for a specific module', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Designing user interface', 'Integrate a third-party payment gateway', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Implementing new features', 'Integrate a third-party payment gateway', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Code review', 'Refactor codebase to follow SOLID principles', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Researching new technologies', 'Design and develop a responsive website layout', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Creating documentation', 'Write unit tests for a specific module', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Meeting with stakeholders', 'Optimize database queries for improved performance', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Deploying software', 'Optimize database queries for improved performance', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Meeting with stakeholders', 'Optimize database queries for improved performance', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Refactoring code', 'Create a documentation guide for API endpoints', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Designing user interface', 'Create a login page with authentication functionality', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Deploying software', 'Refactor codebase to follow SOLID principles', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Code review', 'Implement a chat feature using WebSockets', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Code review', 'Write unit tests for a specific module', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Collaborating with team', 'Implement a chat feature using WebSockets', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Creating documentation', 'Design and develop a responsive website layout', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Code review', 'Develop a mobile app with offline functionality', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Optimizing performance', 'Implement a chat feature using WebSockets', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Debugging', 'Create a documentation guide for API endpoints', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Creating documentation', 'Integrate a third-party payment gateway', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Testing software', 'Integrate a third-party payment gateway', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Designing user interface', 'Develop a mobile app with offline functionality', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Maintaining codebase', 'Develop a mobile app with offline functionality', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Researching new technologies', 'Implement a RESTful API for user management', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Implementing new features', 'Create a login page with authentication functionality', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Creating documentation', 'Implement a chat feature using WebSockets', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Code review', 'Create a login page with authentication functionality', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Writing code', 'Create a login page with authentication functionality', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Debugging', 'Implement a chat feature using WebSockets', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Researching new technologies', 'Write unit tests for a specific module', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Deploying software', 'Write unit tests for a specific module', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Collaborating with team', 'Integrate a third-party payment gateway', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Creating documentation', 'Refactor codebase to follow SOLID principles', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Maintaining codebase', 'Integrate a third-party payment gateway', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Deploying software', 'Refactor codebase to follow SOLID principles', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Optimizing performance', 'Implement a RESTful API for user management', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Code review', 'Write unit tests for a specific module', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Implementing new features', 'Design and develop a responsive website layout', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Writing code', 'Optimize database queries for improved performance', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Researching new technologies', 'Create a login page with authentication functionality', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Implementing new features', 'Design and develop a responsive website layout', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Designing user interface', 'Integrate a third-party payment gateway', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Optimizing performance', 'Optimize database queries for improved performance', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Maintaining codebase', 'Create a documentation guide for API endpoints', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Creating documentation', 'Write unit tests for a specific module', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Maintaining codebase', 'Implement a RESTful API for user management', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Deploying software', 'Write unit tests for a specific module', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Creating documentation', 'Implement a chat feature using WebSockets', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Optimizing performance', 'Create a login page with authentication functionality', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Optimizing performance', 'Design and develop a responsive website layout', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Collaborating with team', 'Design and develop a responsive website layout', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Refactoring code', 'Integrate a third-party payment gateway', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Refactoring code', 'Refactor codebase to follow SOLID principles', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Implementing new features', 'Write unit tests for a specific module', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Implementing new features', 'Create a login page with authentication functionality', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Optimizing performance', 'Integrate a third-party payment gateway', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Writing code', 'Develop a mobile app with offline functionality', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Debugging', 'Implement a RESTful API for user management', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Collaborating with team', 'Develop a mobile app with offline functionality', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Debugging', 'Implement a chat feature using WebSockets', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Researching new technologies', 'Implement a RESTful API for user management', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Creating documentation', 'Refactor codebase to follow SOLID principles', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Troubleshooting issues', 'Implement a chat feature using WebSockets', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Researching new technologies', 'Implement a RESTful API for user management', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Creating documentation', 'Integrate a third-party payment gateway', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Code review', 'Create a login page with authentication functionality', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Researching new technologies', 'Implement a chat feature using WebSockets', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Implementing new features', 'Implement a chat feature using WebSockets', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Writing code', 'Integrate a third-party payment gateway', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Code review', 'Create a documentation guide for API endpoints', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Testing software', 'Create a login page with authentication functionality', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Implementing new features', 'Write unit tests for a specific module', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Researching new technologies', 'Develop a mobile app with offline functionality', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Deploying software', 'Implement a chat feature using WebSockets', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Collaborating with team', 'Implement a chat feature using WebSockets', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Testing software', 'Integrate a third-party payment gateway', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Optimizing performance', 'Design and develop a responsive website layout', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Code review', 'Design and develop a responsive website layout', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Writing code', 'Implement a chat feature using WebSockets', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Writing code', 'Implement a RESTful API for user management', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Writing code', 'Optimize database queries for improved performance', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Implementing new features', 'Refactor codebase to follow SOLID principles', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Code review', 'Implement a chat feature using WebSockets', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Researching new technologies', 'Design and develop a responsive website layout', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Maintaining codebase', 'Integrate a third-party payment gateway', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Debugging', 'Integrate a third-party payment gateway', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Troubleshooting issues', 'Refactor codebase to follow SOLID principles', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Implementing new features', 'Design and develop a responsive website layout', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Researching new technologies', 'Create a documentation guide for API endpoints', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Creating documentation', 'Write unit tests for a specific module', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Collaborating with team', 'Develop a mobile app with offline functionality', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Researching new technologies', 'Design and develop a responsive website layout', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Refactoring code', 'Implement a RESTful API for user management', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Refactoring code', 'Design and develop a responsive website layout', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Refactoring code', 'Implement a RESTful API for user management', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Creating documentation', 'Develop a mobile app with offline functionality', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Troubleshooting issues', 'Create a documentation guide for API endpoints', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Deploying software', 'Develop a mobile app with offline functionality', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Deploying software', 'Implement a RESTful API for user management', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Debugging', 'Design and develop a responsive website layout', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Testing software', 'Implement a chat feature using WebSockets', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Implementing new features', 'Write unit tests for a specific module', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Code review', 'Integrate a third-party payment gateway', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Collaborating with team', 'Develop a mobile app with offline functionality', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Writing code', 'Create a login page with authentication functionality', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Maintaining codebase', 'Integrate a third-party payment gateway', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Code review', 'Implement a RESTful API for user management', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Meeting with stakeholders', 'Write unit tests for a specific module', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Writing code', 'Implement a chat feature using WebSockets', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Optimizing performance', 'Implement a chat feature using WebSockets', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Refactoring code', 'Implement a RESTful API for user management', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Researching new technologies', 'Implement a RESTful API for user management', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Refactoring code', 'Create a login page with authentication functionality', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Code review', 'Create a login page with authentication functionality', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Writing code', 'Implement a chat feature using WebSockets', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Collaborating with team', 'Implement a RESTful API for user management', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Maintaining codebase', 'Create a documentation guide for API endpoints', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Deploying software', 'Create a login page with authentication functionality', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Implementing new features', 'Write unit tests for a specific module', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Maintaining codebase', 'Write unit tests for a specific module', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Code review', 'Design and develop a responsive website layout', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Designing user interface', 'Optimize database queries for improved performance', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Testing software', 'Create a documentation guide for API endpoints', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Designing user interface', 'Write unit tests for a specific module', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Designing user interface', 'Optimize database queries for improved performance', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Testing software', 'Create a documentation guide for API endpoints', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Creating documentation', 'Write unit tests for a specific module', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Writing code', 'Refactor codebase to follow SOLID principles', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Researching new technologies', 'Optimize database queries for improved performance', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Collaborating with team', 'Implement a chat feature using WebSockets', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Testing software', 'Optimize database queries for improved performance', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Optimizing performance', 'Implement a RESTful API for user management', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Testing software', 'Create a documentation guide for API endpoints', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Meeting with stakeholders', 'Write unit tests for a specific module', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Meeting with stakeholders', 'Develop a mobile app with offline functionality', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Deploying software', 'Implement a RESTful API for user management', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Optimizing performance', 'Implement a chat feature using WebSockets', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Debugging', 'Implement a RESTful API for user management', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Code review', 'Implement a RESTful API for user management', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Creating documentation', 'Implement a chat feature using WebSockets', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Implementing new features', 'Implement a chat feature using WebSockets', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Creating documentation', 'Integrate a third-party payment gateway', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Collaborating with team', 'Implement a RESTful API for user management', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Deploying software', 'Design and develop a responsive website layout', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Researching new technologies', 'Optimize database queries for improved performance', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Researching new technologies', 'Implement a RESTful API for user management', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Debugging', 'Create a login page with authentication functionality', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Researching new technologies', 'Create a documentation guide for API endpoints', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Debugging', 'Create a login page with authentication functionality', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Implementing new features', 'Write unit tests for a specific module', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Optimizing performance', 'Create a documentation guide for API endpoints', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Deploying software', 'Develop a mobile app with offline functionality', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Designing user interface', 'Refactor codebase to follow SOLID principles', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Troubleshooting issues', 'Refactor codebase to follow SOLID principles', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Implementing new features', 'Write unit tests for a specific module', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Code review', 'Refactor codebase to follow SOLID principles', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Designing user interface', 'Create a documentation guide for API endpoints', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Testing software', 'Write unit tests for a specific module', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Creating documentation', 'Implement a chat feature using WebSockets', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Maintaining codebase', 'Integrate a third-party payment gateway', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Code review', 'Optimize database queries for improved performance', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Collaborating with team', 'Integrate a third-party payment gateway', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Designing user interface', 'Optimize database queries for improved performance', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Writing code', 'Design and develop a responsive website layout', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Refactoring code', 'Refactor codebase to follow SOLID principles', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Creating documentation', 'Design and develop a responsive website layout', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Designing user interface', 'Write unit tests for a specific module', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Creating documentation', 'Develop a mobile app with offline functionality', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Maintaining codebase', 'Refactor codebase to follow SOLID principles', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Designing user interface', 'Develop a mobile app with offline functionality', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Maintaining codebase', 'Create a login page with authentication functionality', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Maintaining codebase', 'Optimize database queries for improved performance', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Troubleshooting issues', 'Design and develop a responsive website layout', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Troubleshooting issues', 'Integrate a third-party payment gateway', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Creating documentation', 'Implement a RESTful API for user management', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Designing user interface', 'Develop a mobile app with offline functionality', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Testing software', 'Design and develop a responsive website layout', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Writing code', 'Design and develop a responsive website layout', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Debugging', 'Create a documentation guide for API endpoints', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Code review', 'Design and develop a responsive website layout', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Researching new technologies', 'Develop a mobile app with offline functionality', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Troubleshooting issues', 'Implement a RESTful API for user management', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Optimizing performance', 'Create a documentation guide for API endpoints', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Deploying software', 'Optimize database queries for improved performance', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Researching new technologies', 'Refactor codebase to follow SOLID principles', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Researching new technologies', 'Implement a chat feature using WebSockets', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Designing user interface', 'Integrate a third-party payment gateway', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Troubleshooting issues', 'Develop a mobile app with offline functionality', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Meeting with stakeholders', 'Create a login page with authentication functionality', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Code review', 'Write unit tests for a specific module', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Writing code', 'Optimize database queries for improved performance', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Meeting with stakeholders', 'Write unit tests for a specific module', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Designing user interface', 'Integrate a third-party payment gateway', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Code review', 'Develop a mobile app with offline functionality', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Deploying software', 'Design and develop a responsive website layout', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Testing software', 'Create a documentation guide for API endpoints', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Maintaining codebase', 'Create a documentation guide for API endpoints', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Code review', 'Design and develop a responsive website layout', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Troubleshooting issues', 'Implement a chat feature using WebSockets', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Collaborating with team', 'Create a documentation guide for API endpoints', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Designing user interface', 'Optimize database queries for improved performance', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Implementing new features', 'Integrate a third-party payment gateway', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Writing code', 'Write unit tests for a specific module', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Refactoring code', 'Integrate a third-party payment gateway', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Researching new technologies', 'Optimize database queries for improved performance', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Meeting with stakeholders', 'Refactor codebase to follow SOLID principles', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Collaborating with team', 'Implement a chat feature using WebSockets', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Deploying software', 'Design and develop a responsive website layout', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Researching new technologies', 'Develop a mobile app with offline functionality', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Refactoring code', 'Design and develop a responsive website layout', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Maintaining codebase', 'Create a documentation guide for API endpoints', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Designing user interface', 'Implement a RESTful API for user management', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Deploying software', 'Create a login page with authentication functionality', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Designing user interface', 'Write unit tests for a specific module', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Implementing new features', 'Write unit tests for a specific module', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Debugging', 'Implement a chat feature using WebSockets', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Testing software', 'Write unit tests for a specific module', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Debugging', 'Refactor codebase to follow SOLID principles', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Debugging', 'Develop a mobile app with offline functionality', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Researching new technologies', 'Integrate a third-party payment gateway', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Maintaining codebase', 'Implement a RESTful API for user management', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Maintaining codebase', 'Create a documentation guide for API endpoints', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Refactoring code', 'Optimize database queries for improved performance', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Collaborating with team', 'Write unit tests for a specific module', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Writing code', 'Write unit tests for a specific module', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Refactoring code', 'Write unit tests for a specific module', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Refactoring code', 'Develop a mobile app with offline functionality', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Researching new technologies', 'Create a documentation guide for API endpoints', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Creating documentation', 'Develop a mobile app with offline functionality', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Creating documentation', 'Write unit tests for a specific module', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Maintaining codebase', 'Design and develop a responsive website layout', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Implementing new features', 'Develop a mobile app with offline functionality', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Refactoring code', 'Optimize database queries for improved performance', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Collaborating with team', 'Design and develop a responsive website layout', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Creating documentation', 'Implement a RESTful API for user management', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Debugging', 'Create a login page with authentication functionality', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Optimizing performance', 'Write unit tests for a specific module', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Researching new technologies', 'Integrate a third-party payment gateway', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Maintaining codebase', 'Implement a RESTful API for user management', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Debugging', 'Implement a chat feature using WebSockets', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Designing user interface', 'Create a login page with authentication functionality', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Creating documentation', 'Write unit tests for a specific module', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Maintaining codebase', 'Optimize database queries for improved performance', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Meeting with stakeholders', 'Implement a chat feature using WebSockets', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Maintaining codebase', 'Create a documentation guide for API endpoints', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Optimizing performance', 'Create a documentation guide for API endpoints', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Collaborating with team', 'Refactor codebase to follow SOLID principles', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Deploying software', 'Implement a RESTful API for user management', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Refactoring code', 'Design and develop a responsive website layout', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Collaborating with team', 'Create a login page with authentication functionality', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Meeting with stakeholders', 'Write unit tests for a specific module', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Researching new technologies', 'Create a login page with authentication functionality', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Creating documentation', 'Create a documentation guide for API endpoints', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Meeting with stakeholders', 'Design and develop a responsive website layout', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (1, 'Creating documentation', 'Refactor codebase to follow SOLID principles', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Maintaining codebase', 'Develop a mobile app with offline functionality', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Meeting with stakeholders', 'Create a documentation guide for API endpoints', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Optimizing performance', 'Create a documentation guide for API endpoints', 6);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Researching new technologies', 'Design and develop a responsive website layout', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Maintaining codebase', 'Create a login page with authentication functionality', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Maintaining codebase', 'Design and develop a responsive website layout', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Implementing new features', 'Implement a chat feature using WebSockets', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (4, 'Creating documentation', 'Implement a RESTful API for user management', 4);
insert into public.tasks (project_id, title, description, task_type_id) values (2, 'Refactoring code', 'Implement a chat feature using WebSockets', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Testing software', 'Implement a RESTful API for user management', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Testing software', 'Implement a chat feature using WebSockets', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (8, 'Collaborating with team', 'Design and develop a responsive website layout', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Writing code', 'Write unit tests for a specific module', 9);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Collaborating with team', 'Refactor codebase to follow SOLID principles', 7);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Researching new technologies', 'Design and develop a responsive website layout', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Testing software', 'Implement a RESTful API for user management', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Meeting with stakeholders', 'Implement a RESTful API for user management', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Debugging', 'Implement a RESTful API for user management', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Researching new technologies', 'Design and develop a responsive website layout', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (6, 'Testing software', 'Implement a RESTful API for user management', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Refactoring code', 'Create a documentation guide for API endpoints', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (9, 'Code review', 'Implement a RESTful API for user management', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Refactoring code', 'Optimize database queries for improved performance', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (5, 'Troubleshooting issues', 'Refactor codebase to follow SOLID principles', 2);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Meeting with stakeholders', 'Implement a chat feature using WebSockets', 1);
insert into public.tasks (project_id, title, description, task_type_id) values (7, 'Refactoring code', 'Integrate a third-party payment gateway', 8);
insert into public.tasks (project_id, title, description, task_type_id) values (10, 'Maintaining codebase', 'Create a documentation guide for API endpoints', 5);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Troubleshooting issues', 'Optimize database queries for improved performance', 10);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Debugging', 'Develop a mobile app with offline functionality', 3);
insert into public.tasks (project_id, title, description, task_type_id) values (3, 'Troubleshooting issues', 'Create a documentation guide for API endpoints', 2);
